<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
		&times;
	</button>
	<h4 class="modal-title" id="myModalLabel">Crear Convenio</h4>
</div>
<div class="modal-body">
	<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<br/>
					<input type="text" class="form-control" placeholder=" Nombre del Convenio" required="">
					<br/>
				</div>
			</div>
		</div>	
	</form>
</div>
<div class="modal-footer">
	<button type="submit" class="btn btn-default">Crear Convenio</button>
</div>
