<section id="widget-grid" class="">
    <div class="row">
      <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
        <h1 class="page-title txt-color-blueDark">
          <i class="fa-fw fa fa-briefcase"></i> Empresas</h1>
      </div>
    </div>
      
    <div class="row">
      <article id="msgbox" class="col-sm-12">
        <div class="alert alert-success fade in"><button class="close" data-dismiss="alert"><i class="fa-fw fa fa-times-circle"></i></button><i class="fa-fw fa fa-check"></i><strong>Success</strong> The page has been added.</div>
      </article>
    </div>

    <div class="row">
        
        <article class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
          <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">
            
            <header>
              <span class="widget-icon"> <i class="fa fa-list"></i> </span>
              <h2>Listado de empresas</h2>                      
            </header>

            <div>
              <div class="jarviswidget-editbox"></div>
              <div class="widget-body no-padding">

                <table id="dt_basic" class="table table-striped table-bordered table-hover" width="100%">
                  <thead>                     
                    <tr>
                      <th data-hide="phone">NIT</th>
                      <th data-class="expand">Razon Socical</th>
                      <th data-class="expand">Dirección</th>
                      <th data-hide="phone,tablet">Telefono</th>
                      <th data-hide="phone,tablet">Email</th>
                      <!-- <th data-hide="phone">Observaciones</th> -->
                      <th data-hide="phone,tablet">Obser..</th>

                    </tr>
                  </thead>
                  <tbody>
                    <?php 
                      foreach($this->enterprises as $enterprise){
                        echo '<tr>';
                        echo '<td>'.$enterprise['e_nit'].'</td>';
                        echo '<td>'.strtoupper($enterprise['e_razon_social']).'</td>';
                        echo '<td>'.$enterprise['e_direccion'].'</td>';
                        echo '<td>'.$enterprise['e_telefono'].'</td>';
                        echo '<td>'.$enterprise['e_mail'].'</td>';
                        // echo '<td>'.$enterprise['e_obser'].'</td>';
                        echo '<td>';
                        echo '<a href="/RILE/empresas/'.$enterprise['e_nit'].'/edit" data-toggle="modal" ';
                        echo 'data-target="#newContract" class="btn btn-default btn-xs">';
                        echo 'Ver</a>';
                        echo '</td>';
                        echo '</tr>';
                      }
                    ?>
                  </tbody>
                </table>
              
              </div>
            </div>
          </div>
        </article>
        <div class="modal fade" id="newContract" tabindex="-1" role="dialog" aria-labelledby="remoteModalLabel" aria-hidden="true">  
          <div class="modal-dialog">  
              <div class="modal-content"></div>  
          </div>  
       </div>
        <article class="col-xs-4 col-sm-4 col-md-4 col-l4-8">
          <div class="jarviswidget jarviswidget-color-darken" id="wid-id-1" data-widget-editbutton="false">
            <header>
              <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
              <h2>Crear</h2>                      
            </header>

            <div>
              <div class="jarviswidget-editbox">
                
              </div>
              <div class="widget-body no-padding">

                <form action="/RILE/empresas" method="POST" id="checkout-form" class="smart-form" novalidate="novalidate">
                  <header>
                    Datos Básicos
                  </header>
                  <fieldset>
                    <section>
                      <label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
                        <input type="text" name="emp_nit" placeholder="NIT">
                      </label>
                    </section>
          
                    <section>
                      <label class="input"> <i class="icon-prepend fa fa-briefcase"></i>
                        <input type="text" name="emp_name" placeholder="Razón social">
                      </label>
                    </section>
                    <section>
                        <label class="input"> <i class="icon-prepend fa fa-map-marker"></i>
                          <input type="text" name="emp_address" placeholder="Dirección principal">
                        </label>
                      </section>
                  </fieldset>
                  
                  <header>Datos de Contacto</header>
                  <fieldset>
                      
                      <section>
                        <label class="input"> <i class="icon-prepend fa fa-user"></i>
                          <input type="text" name="emp_contact" placeholder="Contacto">
                        </label>
                      </section>
                      
                      <section>
                        <label class="input"> <i class="icon-prepend fa fa-envelope-o"></i>
                          <input type="email" name="emp_mail" placeholder="Correo electronico">
                        </label>
                      </section>
                      
                      <section>
                        <label class="input"> <i class="icon-prepend fa fa-phone"></i>
                          <input type="tel" name="emp_phone" placeholder="Telefono" data-mask="(999) 999-9999" class="valid">
                        </label>
                      </section>

                  </fieldset>
                    <footer>
                      <button type="submit" class="btn btn-primary">
                        Guardar
                      </button>
                      <!-- <a href="#rile/estudiantes"><span class="menu-item-parent">
                        <button type="button" class="btn btn-info">Limpiar</button>
                        </span>
                      </a> -->
                    </footer>
                </form>

              </div>
            </div>
          </div>
        </article>
      </div>

      </section>

      <script type="text/javascript">
        var empjs = '';
        pageSetUp();
        
        var pagefunction = function() {

      var responsiveHelper_dt_basic = undefined;
      var responsiveHelper_datatable_fixed_column = undefined;
      var responsiveHelper_datatable_col_reorder = undefined;
      var responsiveHelper_datatable_tabletools = undefined;
      
      var breakpointDefinition = {
        tablet : 1024,
        phone : 480
      };

      empjs = $('#dt_basic').dataTable({
        "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>"+
          "t"+
          "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
        "autoWidth" : true,
        "preDrawCallback" : function() {
          // Initialize the responsive datatables helper once.
          if (!responsiveHelper_dt_basic) {
            responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
          }
        },
        "rowCallback" : function(nRow) {
          responsiveHelper_dt_basic.createExpandIcon(nRow);
        },
        "drawCallback" : function(oSettings) {
          responsiveHelper_dt_basic.respond();
        }
      });

    /* END BASIC */
    
    /* COLUMN FILTER  */
      var otable = $('#datatable_fixed_column').DataTable({
        //"bFilter": false,
        //"bInfo": false,
        //"bLengthChange": false
        //"bAutoWidth": false,
        //"bPaginate": false,
        //"bStateSave": true // saves sort state using localStorage
      "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>"+
          "t"+
          "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
      "autoWidth" : true,
      "preDrawCallback" : function() {
        // Initialize the responsive datatables helper once.
        if (!responsiveHelper_datatable_fixed_column) {
          responsiveHelper_datatable_fixed_column = new ResponsiveDatatablesHelper($('#datatable_fixed_column'), breakpointDefinition);
        }
      },
      "rowCallback" : function(nRow) {
        responsiveHelper_datatable_fixed_column.createExpandIcon(nRow);
      },
      "drawCallback" : function(oSettings) {
        responsiveHelper_datatable_fixed_column.respond();
      }   
    
      });
      
      // custom toolbar
      $("div.toolbar").html('<div class="text-right"><img src="img/logo.png" alt="SmartAdmin" style="width: 111px; margin-top: 3px; margin-right: 10px;"></div>');
           
      // Apply the filter
      $("#datatable_fixed_column thead th input[type=text]").on( 'keyup change', function () {
        
          otable
              .column( $(this).parent().index()+':visible' )
              .search( this.value )
              .draw();
              
      } );
      /* END COLUMN FILTER */   
    
    /* COLUMN SHOW - HIDE */
    $('#datatable_col_reorder').dataTable({
      "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'C>r>"+
          "t"+
          "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
      "autoWidth" : true,
      "preDrawCallback" : function() {
        // Initialize the responsive datatables helper once.
        if (!responsiveHelper_datatable_col_reorder) {
          responsiveHelper_datatable_col_reorder = new ResponsiveDatatablesHelper($('#datatable_col_reorder'), breakpointDefinition);
        }
      },
      "rowCallback" : function(nRow) {
        responsiveHelper_datatable_col_reorder.createExpandIcon(nRow);
      },
      "drawCallback" : function(oSettings) {
        responsiveHelper_datatable_col_reorder.respond();
      }     
    });
    
    /* END COLUMN SHOW - HIDE */

    /* TABLETOOLS */
    $('#datatable_tabletools').dataTable({
      
      // Tabletools options: 
      //   https://datatables.net/extensions/tabletools/button_options
      "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
          "t"+
          "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
          "oTableTools": {
             "aButtons": [
               "copy",
               "csv",
               "xls",
                  {
                      "sExtends": "pdf",
                      "sTitle": "SmartAdmin_PDF",
                      "sPdfMessage": "SmartAdmin PDF Export",
                      "sPdfSize": "letter"
                  },
                {
                      "sExtends": "print",
                      "sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
                  }
               ],
              "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
          },
      "autoWidth" : true,
      "preDrawCallback" : function() {
        // Initialize the responsive datatables helper once.
        if (!responsiveHelper_datatable_tabletools) {
          responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
        }
      },
      "rowCallback" : function(nRow) {
        responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
      },
      "drawCallback" : function(oSettings) {
        responsiveHelper_datatable_tabletools.respond();
      }
    });
    
    /* END TABLETOOLS */

    var $checkoutForm = $('#checkout-form').validate({
    // Rules for form validation
      rules : {
        emp_nit : { required : true, digits : true },
        emp_name : { required : true },
        emp_address : { required : true },
        emp_contact : { required : true },
        emp_phone : { required : true },
        emp_mail : { required : true, email : true }
      },
  
      // Messages for form validation
      messages : {
        emp_nit : {
          required : 'El nombre es requerido.',
          digits : 'Es permitido solo numeros.'
        },
        emp_name : {
          required : 'El apellido es requrido.'
        },
        emp_address : {
          required : 'La direecion es requerida.'
        },
        emp_name : {
          required : 'Le razon social es requerida'
        },
        emp_phone : {
          required : 'El numero telefonico es requerido.'
        },
        emp_mail : {
          required : 'El email es requerido.',
          email : 'Formato de email desconocido.'
        }
      },
  
      // Do not change code below
      errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
      }
    });


  };

  // load related plugins
  
  loadScript("assets/js/plugin/datatables/jquery.dataTables.min.js", function(){
    loadScript("assets/js/plugin/datatables/dataTables.colVis.min.js", function(){
      loadScript("assets/js/plugin/datatables/dataTables.tableTools.min.js", function(){
        loadScript("assets/js/plugin/datatables/dataTables.bootstrap.min.js", function(){
          loadScript("assets/js/plugin/datatable-responsive/datatables.responsive.min.js", function(){
            loadScript("assets/js/plugin/jquery-form/jquery-form.min.js", pagefunction);
          });
        });
      });
    });
  });

      </script>