<section id="widget-grid" class="">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h1 class="page-title txt-color-blueDark">
          <i class="fa-fw fa fa-building"></i> Empresas <?php echo strtoupper(Session::get('User'))?></h1>
      </div>
    </div>

    <div class="row">
    <article class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    	<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">
            <header>
              <span class="widget-icon"> <i class="fa fa-file"></i> </span>
              <h2> Curriculum Vitae "Hoja de Vida" </h2>        
            </header>
        	<div>


        	</div>
        	</div>
        </article>
        <article class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    	<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">
            <header>
              <span class="widget-icon"> <i class="fa fa-file"></i> </span>
              <h2> Curriculum Vitae "Hoja de Vida" </h2>        
            </header>
        	<div>


        	</div>
        	</div>
        </article>       
    </div>
</section>