<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>RILE - Ruta de Inserción Laboral Exitosa</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<?php
		$this->getCSS('bootstrap.min'); 
		$this->getCSS('font-awesome.min');
		// $this->getCSS('lockscreen');
		$this->getCSS('login_rile');
		$this->getFavicon();
	?>

</head>
    <style>
        .edgeLoad-EDGE-2579157 { visibility:hidden; }
    </style>
<body>

<div class="contenido_ini">
	<div class="imagenes">
		<!-- img src="assets/img/rile/rile-03.png"-->
		<div id="Stage" class="EDGE-2579157">
	        <div id="Stage_OrangeBox" class="edgeLoad-EDGE-2579157"></div>
	        <div id="Stage_OrangeArrow" class="edgeLoad-EDGE-2579157"></div>
	        <div id="Stage_Exitosa" class="edgeLoad-EDGE-2579157"></div>
	        <div id="Stage_RedBox" class="edgeLoad-EDGE-2579157"></div>
	        <div id="Stage_RedArrow" class="edgeLoad-EDGE-2579157"></div>
	        <div id="Stage_Laboral" class="edgeLoad-EDGE-2579157"></div>
	        <div id="Stage_GreenBox" class="edgeLoad-EDGE-2579157"></div>
	        <div id="Stage_GreenArrow" class="edgeLoad-EDGE-2579157"></div>
	        <div id="Stage_Insercin" class="edgeLoad-EDGE-2579157"></div>
	        <div id="Stage_BlueBox" class="edgeLoad-EDGE-2579157"></div>
	        <div id="Stage_BlueArrow" class="edgeLoad-EDGE-2579157"></div>
	        <div id="Stage_Ruta" class="edgeLoad-EDGE-2579157"></div>
	        <div id="Stage_slogan_rile" class="edgeLoad-EDGE-2579157"></div>
	    </div>
		<div class="ima">
			<img src="assets/img/rile/img-04.png">
			<img src="assets/img/rile/img-05.png">
			<img src="assets/img/rile/img-06.png">
			<img src="assets/img/rile/img-07.png">
		</div>
		<div class="plat">
			<p>La plataforma que asegura la <span>calidad</span>
			de nuestros egresados</p>
			
		</div>
	</div>
	<div class="contenido">
		<div class="inicio">
			<form method="POST" action="#">
				<p>Inicio de Sesión</p>
				<div style="text-align: center">
					<input type="text" id="x_usuario" name="x_usuario" placeholder="Usuario o Email">
					<input type="password" id="x_clave" name="x_clave" placeholder="Contraseña" onkeypress="if (event.keyCode == 13) iniciar_sesion()">
				</div>
				<center style="margin-top: 15px" >
					<a id="olvido" href="recuperar" style="color: #fff">¿Olvidaste la contraseña?</a><br/>
					<a id="res" href="empresas/registro" style="color: #fff">Registrese su Empresa Aqui</a>
				</center>
				<div style="text-align: center; margin-top: 15px">
					<input type="submit" class="ingresar" id="btn" value="Ingresar a la Plataforma">
				</div>
			</form>
		</div>
		<div style="text-align: center; margin-top: 15px">
			<img src="assets/img/rile/acc-03.png">
		</div>
	</div>
</div>


	
<script type="text/javascript" charset="utf-8" src="http://animate.adobe.com/runtime/5.0.1/edge.5.0.1.min.js"></script>
<script>
   AdobeEdge.loadComposition('logo', 'EDGE-2579157', {
    scaleToFit: "none",
    centerStage: "none",
    minW: "0",
    maxW: "undefined",
    width: "457px",
    height: "142px"
}, {"dom":{}}, {"dom":{}});
</script>
</body>
</html>