<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
		&times;
	</button>
	<h4 class="modal-title" id="myModalLabel"><?php echo $this->student['nombre'].' - '.$this->student['e_identificacion']; ?></h4>
</div>

<div class="modal-body">

<ul id="myTab1" class="nav nav-tabs bordered">						
							<li class="active">
								<a href="#s1" data-toggle="tab"><i class="fa fa-lg fa-fw fa-user"></i> Generales</a>
							</li>
							<li>
								<a href="#s2" data-toggle="tab"><i class="fa fa-lg fa-fw fa-graduation-cap"></i> Datos Personales</a>
							</li>
							<li>
								<a href="#s3" data-toggle="tab"><i class="fa fa-fw fa-lg fa-dollar"></i> Referencias</a>
							</li>
							<li>
								<a href="#s4" data-toggle="tab"><i class="fa fa-fw fa-lg fa-dollar"></i> Educacion</a>
							</li>
							<li>
								<a href="#s5" data-toggle="tab"><i class="fa fa-fw fa-lg fa-dollar"></i> Experiencia laboral</a>
							</li>
							<li>
								<a href="#s6" data-toggle="tab"><i class="fa fa-fw fa-lg fa-dollar"></i> Informacion adicional</a>
							</li>
						</ul>
						<!--Prueba para git-->
						<div id="myTabContent1" class="tab-content padding-10">
							<div class="tab-pane fade in active" id="s1">
								<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">
					            	<header>Datos Básicos</header>
						            <fieldset>
						            	<div class="row">
							            	<section class="col col-4">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="number" name="id_estudiante" placeholder="Identificación">
							                    </label>
							                </section>
											<section class="col col-4">
							                	<label class="input"><i class="icon-prepend fa fa-calendar"></i>
							                		<input type="date" name="Fecha_de_expedicion">
							                    </label>
							                </section>
							                <section class="col col-4">
												<label class="select">
													<select class="input-sm" name="Ciudad_de_Expedicion">
														<option value="0">Ciudad de Expedicion</option>
														<option value="1">Alexandra</option>
														<option value="2">Alice</option>
														<option value="3">Anastasia</option>
														<option value="4">Avelina</option>
													</select> <i></i> 
												</label>
											</section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-4">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="number" name="Nro_de_libreta_militar" placeholder="Nro de libreta militar">
							                    </label>
							                </section>
											<section class="col col-4">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-map-marker"></i>
							                    	<input type="text" name="Distrito_militar" placeholder="Distrito militar">
							                    </label>
							                </section>
							                <section class="col col-4">
												<label class="select">
													<select class="input-sm" name="Ciudad_Lib._militar">
														<option value="0">Ciudad Lib. militar</option>
														<option value="1">Alexandra</option>
														<option value="2">Alice</option>
														<option value="3">Anastasia</option>
														<option value="4">Avelina</option>
													</select> <i></i> 
												</label>
											</section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
								            	<label class="input"> <i class="icon-prepend fa fa-user"></i>
								                	<input type="text" name="Nombres" placeholder="Nombres">
								                </label>
							            	</section>
									        <section class="col col-6">
						                        <label class="input"> <i class="icon-prepend fa fa-user"></i>
						                        	<input type="text" name="Apellido" placeholder="Apellido">
						                        </label>
					                    	</section>
					                    </div>
					                    <div class="row">
									        <section class="col col-3">
						                        <label class="input"> <i class="icon-prepend glyphicon glyphicon-map-marker"></i>
						                        	<input type="text" name="Dirección" placeholder="Dirección">
						                        </label>
					                    	</section>
											<section class="col col-3">
									            	<label class="input"> <i class="icon-prepend glyphicon glyphicon-map-marker"></i>
									                	<input type="text" name="Barrio" placeholder="Barrio">
									                </label>
								           	</section>
								           	<section class="col col-3">
												<label class="select">
													<select class="input-sm" name="Estracto">
														<option value="0">Estracto</option>
														<option value="1">1</option>
														<option value="2">2</option>
														<option value="3">3</option>
														<option value="4">4</option>
														<option value="5">5</option>
														<option value="6">6</option>
													</select> <i></i> 
												</label>
											</section>
								           	<section class="col col-3">
												<label class="select">
													<select class="input-sm" name="Ciudad">
														<option value="0">Ciudad</option>
														<option value="1">Alexandra</option>
														<option value="2">Alice</option>
														<option value="3">Anastasia</option>
														<option value="4">Avelina</option>
													</select> <i></i> 
												</label>
											</section>
					                    </div>
										<div class="row">
											<section class="col col-6">
						                        <label class="input"> <i class="icon-prepend fa fa-phone"></i>
						                        	<input type="tel" name="Telefono" placeholder="Telefono" data-mask="999-9999">
						                        </label>
					                    	</section>
					                    	<section class="col col-6">
						                        <label class="input"> <i class="icon-prepend fa fa-mobile"></i>
						                        	<input type="number" name="Celular" placeholder="Celular">
						                        </label>
					                    	</section>
										</div>
										<div class="row">
											<section class="col col-6">
						                        <label class="input"> <i class="icon-prepend fa fa-envelope-o"></i>
						                        	<input type="email" name="Email" placeholder="E-mail">
						                        </label>
					                    	</section>
					                    	<section class="col col-6">
						                        <label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
						                        	<input type="number" name="Pasado_Judicial_No." placeholder="Pasado Judicial No.">
						                        </label>
					                    	</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Licencia_Conducción">
													<i data-swchon-text="ON" data-swchoff-text="OFF"></i>Licencia Conducción
												</label>
					                    	</section>
					                    	<section class="col col-6">
						                        <label class="select">
													<select class="input-sm" name="Categoria">
														<option value="0">Categoria</option>
														<option value="1">1</option>
														<option value="2">2</option>
														<option value="3">3</option>
														<option value="4">4</option>
														<option value="5">5</option>
														<option value="6">6</option>
														<option value="7">7</option>
														<option value="8">8</option>
													</select> <i></i> 
												</label>
					                    	</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Sisben">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Sisben
												</label>
											</section>	
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Pertenencia_a_red_unidos">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Pertenencia a red unidos
												</label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Cetificado_Manipulacion_Alimentos">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Cetificado Manipulacion Alimentos
												</label>
											</section>	
											<section class="col col-6">
												<label class="input"> <i class="icon-prepend fa fa-building"></i>
						                        	<input type="text" name="Expedida_por_1" placeholder="Expedida por">
						                        </label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Certificado_Bioseguridad">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Certificado Bioseguridad
												</label>
											</section>	
											<section class="col col-6">
												<label class="input"> <i class="icon-prepend fa fa-building"></i>
						                        	<input type="text" name="Expedida_por_2" placeholder="Expedida por">
						                        </label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Certificado_de_Trabajo_en_Altura">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Certificado de Trabajo en Altura
												</label>
											</section>	
											<section class="col col-6">
												<label class="input"> <i class="icon-prepend fa fa-building"></i>
						                        	<input type="text" name="Expedida_por_3" placeholder="Expedida por">
						                        </label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Certificado_Conte">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Certificado Conte
												</label>
											</section>	
											<section class="col col-6">
												<label class="input"> <i class="icon-prepend fa fa-building"></i>
						                        	<input type="text" name="Expedida_por_4" placeholder="Expedida por">
						                        </label>
											</section>
										</div>
										<section>
											<label class="textarea textarea-expandable">	
												<textarea rows="3" class="custom-scroll" name="text_area" placeholder="Informacion Adicional"></textarea> 
											</label>
											<div class="note">
												<strong>Nota:</strong> Se expande.
											</div>
										</section>
						            </fieldset>
						            <footer>
											<button type="submit" class="btn btn-primary" name="submit_s1">Enviar</button>
									</footer>
					            </form>														
							</div>
							<div class="tab-pane fade" id="s2">
								<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">
									<header>Datos Personales</header>
					                <fieldset>
					                	<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-calendar"></i>
							                    	<input type="date" name="Fecha_de_nacimiento" placeholder="Fecha de nacimiento">
							                    </label>
							                </section>
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Sexo">
													<i data-swchon-text="M" data-swchoff-text="F"></i>Sexo
												</label>
											</section>
						          		</div>
										<div class="row">
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-suitcase"></i>
							                    	<input type="text" name="Profesión_Oficio" placeholder="Profesión/Oficio">
							                    </label>
							                </section>
											<section class="col col-6">
												<label class="select">
													<select class="input-sm" name="Estado_Civil">
														<option value="0">Estado Civil</option>
														<option value="1">Soltero</option>
														<option value="2">Casado</option>
														<option value="3">Divorciado</option>
														<option value="4">Union Libre</option>
													</select> <i></i> 
												</label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-warning"></i>
							                    	<input type="number" name="Peso" placeholder="Peso">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-warning"></i>
							                    	<input type="number" name="Estatura" placeholder="Estatura">
							                    </label>
							                </section>
										</div>
										<div class="row">
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-warning"></i>
							                    	<input type="number" name="Talla_de_Zapato" placeholder="Talla de Zapato">
							                    </label>
							                </section>
											<section class="col col-6">
												<label class="select">
													<select class="input-sm" name="Tipo_de_sangre">
														<option value="0">Tipo de sangre</option>
														<option value="1">O+</option>
														<option value="2">AB+</option>
														<option value="3">O-</option>
														<option value="4">AB-</option>
														<option value="5">A+</option>
														<option value="6">A-</option>
														<option value="7">B+</option>
														<option value="8">B-</option>
													</select> <i></i> 
												</label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-warning"></i>
							                    	<input type="number" name="Talla_de_Pantalon" placeholder="Talla de Pantalon">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-warning"></i>
							                    	<input type="text" name="Talla_de_Camisa" placeholder="Talla de Camisa">
							                    </label>
							                </section>
										</div>
					                </fieldset>

									<header>
						                Grupo Étnico al que pertenece
						            </header>
									<fieldset>
										<div class="row">
												<section class="col col-4">
													<label class="select">
														<select class="input-sm" name="Grupo_Étnico">
															<option value="0">Grupo Étnico</option>
															<option value="1">Afrocolombiano</option>
															<option value="2">Indigena</option>
															<option value="3">Sin pertenencia étnica</option>
															<option value="4">Otros grupos</option>
														</select> <i></i> 
													</label>
												</section>
												<section class="col col-4">
													<label class="select">
														<select class="input-sm" name="Tipo_de_Étnia">
															<option value="0">Tipo de Étnia</option>
															<option value="1">Afrodecendiente</option>
															<option value="2">Negro</option>
															<option value="3">Palenquero</option>
															<option value="4">Raizal</option>
															<option value="5">Blanco</option>
															<option value="6">Mestizo</option>
															<option value="7">Arabes</option>
															<option value="8">Judios</option>
															<option value="9">Rom-Gitanos</option>
															<option value="10">Otros</option>
															<option value="11">N/A</option>
														</select> <i></i> 
													</label>
												</section>
											</div>
									</fieldset>

									<header>
						                Grupo social al que pertenece
						            </header>
						            <fieldset>
						            	<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Madre_cabeza_de_familia">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Madre cabeza de familia
												</label>
											</section>	
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Desplazado_por_la_violencia">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Desplazado por la violencia
												</label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Desplazado_por_fenomeno_natural">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Desplazado por fenomeno natural
												</label>
											</section>	
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Reinsertado">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Reinsertado
												</label>
											</section>	
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Discapacitado">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Discapacitado 	
												</label>
											</section>	
											<section class="col col-6">
												<label class="input"> <i class="icon-prepend fa fa-wheelchair"></i>
						                        	<input type="text" name="Discapacidad" placeholder="Discapacidad">
						                        </label>
											</section>
										</div>
						            </fieldset>
									<footer>
											<button type="submit" class="btn btn-primary" name="submit_s2">Enviar</button>
									</footer>
								</form>
							</div>
							
						     <div class="tab-pane fade" id="s3">
								<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">

									<header>
						                Familiares
						            </header>
						            <fieldset>
						            	<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-user"></i>
							                    	<input type="text" name="Nombre_Ref_Familiar" placeholder="Nombre">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-group"></i>
							                    	<input type="text" name="Parentesco" placeholder="Parentesco">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-warning"></i>
							                    	<input type="number" name="Edad" placeholder="Edad">
							                    </label>
							                </section>
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Sexo">
													<i data-swchon-text="M" data-swchoff-text="F"></i>Sexo
												</label>
											</section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-suitcase"></i>
							                    	<input type="text" name="Ocupación" placeholder="Ocupación">
							                    </label>
							                </section>
											<section class="col col-6">
													<label class="select">
														<select class="input-sm" name="Nivel_de_escolaridad">
															<option value="0">Nivel de escolaridad</option>
															<option value="1">Bachiller</option>
															<option value="2">Técnico</option>
															<option value="3">Técnologo</option>
															<option value="4">Profesional</option>
															<option value="5">Basica Primaria</option>
														</select><i></i> 
													</label>
												</section>
						          		</div>
						            </fieldset>
									<header>
						                Personales
						            </header>
						            <fieldset>
						            	<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-user"></i>
							                    	<input type="text" name="Nombre_Ref_Persoles" placeholder="Nombre">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-group"></i>
							                    	<input type="text" name="Parentesco_Ref_Personal" placeholder="Parentesco">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-map-marker"></i>
							                    	<input type="text" name="Direccion_Ref_Personal" placeholder="Direccion">
							                    </label>
							                </section>
											<section class="col col-6">
													<label class="select">
														<select class="input-sm" name="Ciudad_Ref_Personal">
															<option value="0">Ciudad</option>
															<option value="1">Bachiller</option>
															<option value="2">Técnico</option>
															<option value="3">Técnologo</option>
															<option value="4">Profesional</option>
															<option value="5">Basica Primaria</option>
														</select> <i></i> 
													</label>
												</section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-phone"></i>
							                    	<input type="tel" name="Telefono_Ref_Personal" placeholder="Telefono" data-mask="999-9999">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-mobile"></i>
							                    	<input type="number" name="Celular_Ref_Personal" placeholder="Celular">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-suitcase"></i>
							                    	<input type="text" name="Profesión_Ref_Personal" placeholder="Profesión">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-building"></i>
							                    	<input type="text" name="Empresa_donde_labora" placeholder="Empresa donde labora">
							                    </label>
							                </section>
						          		</div>
						            </fieldset>
						            <footer>
											<button type="submit" class="btn btn-primary" name="submit_s3">Enviar</button>
									</footer>
						         </form>
						     </div>
						     <div class="tab-pane fade" id="s4">
								<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">
									<header>
						                Educación
						            </header>
						            <fieldset>
						            	<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-institution"></i>
							                    	<input type="text" name="Institucion" placeholder="Institucion">
							                    </label>
							                </section>
											<section class="col col-6">
													<label class="select">
														<select class="input-sm" name="Nivel">
															<option value="0">Nivel</option>
															<option value="1">Bachiller</option>
															<option value="2">Técnico</option>
															<option value="3">Técnologo</option>
															<option value="4">Profesional</option>
															<option value="5">Basica Primaria</option>
														</select> <i></i> 
													</label>
												</section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-calendar"></i>
							                    	<input type="date" name="Fecha_de_inicio" placeholder="Fecha de inicio">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-calendar"></i>
							                    	<input type="date" name="Fecha_de_finalizacion" placeholder="Fecha de finalizacion">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-graduation-cap"></i>
							                    	<input type="text" name="Titulo" placeholder="Titulo">
							                    </label>
							                </section>
											<section class="col col-6">
													<label class="select">
														<select class="input-sm" name="Ciudad_Educacion">
															<option value="0">Ciudad</option>
															<option value="1">Bachiller</option>
															<option value="2">Técnico</option>
															<option value="3">Técnologo</option>
															<option value="4">Profesional</option>
															<option value="5">Basica Primaria</option>
														</select> <i></i> 
													</label>
												</section>
						          		</div>
						            </fieldset>
						            <footer>
											<button type="submit" class="btn btn-primary" name="submit_s4">Enviar</button>
									</footer>
						         </form>
						     </div>
						     <div class="tab-pane fade" id="s5">
								<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">
									<header>
						                Idioma
						            </header>
						            <fieldset>
						            	<div class="row">
						            		<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-globe"></i>
							                    	<input type="text" name="Idioma" placeholder="Idioma">
							                    </label>
							                </section>
							                <section class="col col-6">
													<label class="select">
														<select class="input-sm" name="Lee">
															<option value="0">Lee</option>
															<option value="1">E</option>
															<option value="2">B</option>
															<option value="3">M</option>
														</select> <i></i> 
													</label>
							                </section>
						            	</div>
						            	<div class="row">
						            		<section class="col col-6">
													<label class="select">
														<select class="input-sm" name="Habla">
															<option value="0">Habla</option>
															<option value="1">E</option>
															<option value="2">B</option>
															<option value="3">M</option>
														</select> <i></i> 
													</label>
							                </section>
							                <section class="col col-6">
													<label class="select">
														<select class="input-sm" name="Escribe">
															<option value="0">Escribe</option>
															<option value="1">E</option>
															<option value="2">B</option>
															<option value="3">M</option>
														</select> <i></i> 
													</label>
							                </section>
						            	</div>
						            </fieldset>
									<header>
						                Experiencia Laboral
						            </header>
						            <fieldset>
						            	<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-building"></i>
							                    	<input type="text" name="Empresa" placeholder="Empresa">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-user"></i>
							                    	<input type="text" name="Cargo" placeholder="Cargo">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-calendar"></i>
							                    	<input type="date" name="Fecha_de_inicio_Laboral" placeholder="Fecha de inicio">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-calendar"></i>
							                    	<input type="date" name="Fecha_de_finalizacion_Laboral" placeholder="Fecha de finalizacion">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-gears"></i>
							                    	<input type="text" name="Funciones" placeholder="Funciones">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-phone"></i>
							                    	<input type="number" name="Teléfono_Exp_Laboral" placeholder="Teléfono">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-user"></i>
							                    	<input type="text" name="Nombre_del_Jefe_inmediato" placeholder="Nombre del Jefe inmediato">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend fa fa-warning"></i>
							                    	<input type="text" name="Motivo_de_retiro" placeholder="Motivo de retiro">
							                    </label>
							                </section>
						          		</div>
						            </fieldset>
						            <footer>
											<button type="submit" class="btn btn-primary" name="submit_s5">Enviar</button>
									</footer>
						         </form>
						     </div>
						     
						     <div class="tab-pane fade" id="s6">
								<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">
									<header>
							                Informacion Bancaria
							            </header>
							            <fieldset>
							            	<div class="row">
								            	<section class="col col-6">
													<label class="toggle">
														<input type="checkbox" name="Cuenta_Bancaria">
														<i data-swchon-text="SI" data-swchoff-text="NO"></i>Cuenta Bancaria
													</label>
												</section>
												<section class="col col-6">
														<label class="select">
															<select class="input-sm" name="Tipo_de_cuenta">
																<option value="0">Tipo de cuenta</option>
																<option value="1">Ceunta de ahorro</option>
																<option value="2">Cuenta corriente</option>
															</select> <i></i> 
														</label>
								                </section>
							          		</div>
							          		<div class="row">
								            	<section class="col col-6">
								                	<label class="input"> <i class="icon-prepend fa fa-bank"></i>
								                    	<input type="text" name="Banco" placeholder="Banco">
								                    </label>
								                </section>
												<section class="col col-6">
													<label class="toggle">
														<input type="checkbox" name="Esta_Activa">
														<i data-swchon-text="SI" data-swchoff-text="NO"></i>¿Esta Activa?
													</label>
												</section>
							          		</div>
							            </fieldset>
									<header>
						                Informacion adicional
						            </header>
						            <fieldset>
						            	<div class="row">
							            	<section class="col col-6">
													<label class="select">
														<select class="input-sm" name="Vivienda_en_la_que_habita">
															<option value="0">Vivienda en la que habita</option>
															<option value="1">Propia</option>
															<option value="2">Alquilada</option>
															<option value="3">Invasión</option>
															<option value="4">Familiar</option>
														</select> <i></i> 
													</label>
							                </section>
											<section class="col col-6">
													<label class="select">
														<select class="input-sm" name="Mat_de_los_exteriores_de_la_vivienda">
															<option value="0">Material de los exteriores de la vivienda</option>
															<option value="1">Ladrillo/Bloque</option>
															<option value="2">Material prefabricado</option>
															<option value="2">Madera pulida</option>
															<option value="2">Piedra</option>
															<option value="2">Adobe</option>
															<option value="2">Baldosin</option>
															<option value="2">Unisol</option>
															<option value="2">Marmol</option>
															<option value="2">Alfombra/Tapete</option>
														</select> <i></i> 
													</label>
							                </section>
						          		</div>
						          		<div class="row">
						          		<label>¿Cuenta con servivios publicos?</label><br>
							            	<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Agua">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Agua
												</label>
											</section>
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Energia">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Energia Electrica
												</label>
											</section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Alcantarillado">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Alcantarillado 	
												</label>
											</section>
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="Gas">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Gas
												</label>
											</section>
						          		</div>
						          		<div class="row">
						          		<section section class="col col-4">
												<label class="toggle">
													<input type="checkbox" name="Télefono_Servicios_Publicos">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Télefono
												</label>
											</section>
						          			<section class="col col-4">
												<label class="toggle">
													<input type="checkbox" name="Conyugue">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Conyugue
												</label>
											</section>
							            	<section class="col col-4">
												<label class="toggle">
													<input type="checkbox" name="Trabaja_conyugue">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Trabaja
												</label>
											</section>
						          		</div>
						          		<div class="row">
						          			<section>
							                	<label class="input"> <i class="icon-prepend fa fa-money"></i>
							                    	<input type="text" name="Promedio_de_ingreso_mensual" placeholder="Promedio de ingreso mensual">
							                    </label>
							                </section>
						          		</div>
						            </fieldset>
						            <footer>
											<button type="submit" class="btn btn-primary" name="submit_s6">Enviar</button>
									</footer>
						         </form>
						     </div>
						</div>
						<div class="modal fade" id="newContract" tabindex="-1" role="dialog" aria-labelledby="remoteModalLabel" aria-hidden="true">  
						     <div class="modal-dialog modal-lg">  
						         <div class="modal-content">
						            
						         </div>  
						     </div>
						</div>	

<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">
		Cerrar
	</button>
</div>