<section id="widget-grid" class="">
    <div class="row">
      <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
        <h1 class="page-title txt-color-blueDark">
          <i class="fa-fw fa fa-graduation-cap"></i> Estudiantes</h1>
      </div>
    </div>

    <div class="row">
        
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          
          <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">

            <header>
              <span class="widget-icon"> <i class="fa fa-search"></i> </span>
              <h2>Consulta</h2>        
              
            </header>

            <!-- widget div-->
            <div>
              
              <!-- widget edit box -->
              <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->
                
              </div>
              <!-- end widget edit box -->
              
              <!-- widget content -->
             <div class="widget-body no-padding">

            <table id="dt_basic" class="table table-striped table-bordered table-hover" width="100%">
              <thead>                     
                <tr>
                  <th data-hide="phone">Identificación</th>
                  <th data-class="expand">Name</th>
                  <th data-hide="phone,tablet">Covenio</th>
                  <th data-hide="phone,tablet">Programa</th>
                  <th data-hide="phone,tablet">Estado</th>
                  <th data-hide="phone">F/M</th>
                  <th data-hide="phone,tablet">Acciones</th>
                </tr>
              </thead>
              <tbody>
                <?php 
                  foreach($this->students as $student){
                    echo '<tr>';
                    echo '<td>'.$student['e_identificacion'].'</td>';
                    echo '<td>'.strtoupper($student['nombre']).'</td>';
                    echo '<td>'.$student['convenio'].'</td>';
                    echo '<td>'.$student['programa'].'</td>';
                    echo '<td>';
                    if ($student['asp_apt'] === 'Apto'){
                      echo '<span class="label label-success">Apto</span>';
                    }else{
                      if($student['asp_apt'] === 'Sena'){
                        echo '<span class="label label-primary">Sena</span>';
                      }else{
                        echo '<span class="label label-danger">No Apto</span>';
                      }
                    }
                    echo '</td>';
                    echo '<td><center>';
                    if($student['e_genero'] == 1){
                      echo '<i class="fa fa-male" style="color: blue"></i><span style="display: none;">femenino</span>'  ;
                    }else{
                      echo  '<i class="fa fa-female" style="color: pink"></i><span style="display: none;">masculino</span>';
                    }
                    echo '</center></td>';
                    echo '<td>';
                       echo '<a href="/RILE/estudiantes/'.$student['e_id'].'" data-toggle="modal" ';
                       echo 'data-target="#newContract" class="btn btn-default btn-xs">';
                       echo 'Mostar</a>';
                       echo '<a href="/RILE/estudiantes/'.$student['e_id'].'/edit" data-toggle="modal" ';
                       echo 'data-target="#newContract" class="btn btn-default btn-xs">';
                       echo 'Editar</a>';
                       echo '</td>';
                    echo '</tr>';
                  }
                ?>
              </tbody>
            </table>

          </div>

<div class="modal fade" id="newContract" tabindex="-1" role="dialog" aria-labelledby="remoteModalLabel" aria-hidden="true">  
     <div class="modal-dialog">  
         <div class="modal-content">
            
         </div>  
     </div>  
 </div>
              <!-- end widget content -->
              
            </div>
            <!-- end widget div -->
            
          </div>
          <!-- end widget -->

        </article>
        <!-- WIDGET END -->
        
      </div>

      </section>

      <script type="text/javascript">
        pageSetUp();

        var pagefunction = function() {

        }
        
        var pagefunction = function() {

    //console.log("cleared");
    
    /* // DOM Position key index //
    
      l - Length changing (dropdown)
      f - Filtering input (search)
      t - The Table! (datatable)
      i - Information (records)
      p - Pagination (paging)
      r - pRocessing 
      < and > - div elements
      <"#id" and > - div with an id
      <"class" and > - div with a class
      <"#id.class" and > - div with an id and class
      
      Also see: http://legacy.datatables.net/usage/features
    */  

    /* BASIC ;*/
      var responsiveHelper_dt_basic = undefined;
      var responsiveHelper_datatable_fixed_column = undefined;
      var responsiveHelper_datatable_col_reorder = undefined;
      var responsiveHelper_datatable_tabletools = undefined;
      
      var breakpointDefinition = {
        tablet : 1024,
        phone : 480
      };

      $('#dt_basic').dataTable({
        "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>"+
          "t"+
          "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
        "autoWidth" : true,
        "preDrawCallback" : function() {
          // Initialize the responsive datatables helper once.
          if (!responsiveHelper_dt_basic) {
            responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
          }
        },
        "rowCallback" : function(nRow) {
          responsiveHelper_dt_basic.createExpandIcon(nRow);
        },
        "drawCallback" : function(oSettings) {
          responsiveHelper_dt_basic.respond();
        }
      });

    /* END BASIC */
    
    /* COLUMN FILTER  */
      var otable = $('#datatable_fixed_column').DataTable({
        //"bFilter": false,
        //"bInfo": false,
        //"bLengthChange": false
        //"bAutoWidth": false,
        //"bPaginate": false,
        //"bStateSave": true // saves sort state using localStorage
      "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6 hidden-xs'f><'col-sm-6 col-xs-12 hidden-xs'<'toolbar'>>r>"+
          "t"+
          "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
      "autoWidth" : true,
      "preDrawCallback" : function() {
        // Initialize the responsive datatables helper once.
        if (!responsiveHelper_datatable_fixed_column) {
          responsiveHelper_datatable_fixed_column = new ResponsiveDatatablesHelper($('#datatable_fixed_column'), breakpointDefinition);
        }
      },
      "rowCallback" : function(nRow) {
        responsiveHelper_datatable_fixed_column.createExpandIcon(nRow);
      },
      "drawCallback" : function(oSettings) {
        responsiveHelper_datatable_fixed_column.respond();
      }   
    
      });
      
      // custom toolbar
      $("div.toolbar").html('<div class="text-right"><img src="img/logo.png" alt="SmartAdmin" style="width: 111px; margin-top: 3px; margin-right: 10px;"></div>');
           
      // Apply the filter
      $("#datatable_fixed_column thead th input[type=text]").on( 'keyup change', function () {
        
          otable
              .column( $(this).parent().index()+':visible' )
              .search( this.value )
              .draw();
              
      } );
      /* END COLUMN FILTER */   
    
    /* COLUMN SHOW - HIDE */
    $('#datatable_col_reorder').dataTable({
      "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'C>r>"+
          "t"+
          "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
      "autoWidth" : true,
      "preDrawCallback" : function() {
        // Initialize the responsive datatables helper once.
        if (!responsiveHelper_datatable_col_reorder) {
          responsiveHelper_datatable_col_reorder = new ResponsiveDatatablesHelper($('#datatable_col_reorder'), breakpointDefinition);
        }
      },
      "rowCallback" : function(nRow) {
        responsiveHelper_datatable_col_reorder.createExpandIcon(nRow);
      },
      "drawCallback" : function(oSettings) {
        responsiveHelper_datatable_col_reorder.respond();
      }     
    });
    
    /* END COLUMN SHOW - HIDE */

    /* TABLETOOLS */
    $('#datatable_tabletools').dataTable({
      
      // Tabletools options: 
      //   https://datatables.net/extensions/tabletools/button_options
      "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
          "t"+
          "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
          "oTableTools": {
             "aButtons": [
               "copy",
               "csv",
               "xls",
                  {
                      "sExtends": "pdf",
                      "sTitle": "SmartAdmin_PDF",
                      "sPdfMessage": "SmartAdmin PDF Export",
                      "sPdfSize": "letter"
                  },
                {
                      "sExtends": "print",
                      "sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
                  }
               ],
              "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
          },
      "autoWidth" : true,
      "preDrawCallback" : function() {
        // Initialize the responsive datatables helper once.
        if (!responsiveHelper_datatable_tabletools) {
          responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
        }
      },
      "rowCallback" : function(nRow) {
        responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
      },
      "drawCallback" : function(oSettings) {
        responsiveHelper_datatable_tabletools.respond();
      }
    });
    
    /* END TABLETOOLS */

  };

  // load related plugins
  
  loadScript("assets/js/plugin/datatables/jquery.dataTables.min.js", function(){
    loadScript("assets/js/plugin/datatables/dataTables.colVis.min.js", function(){
      loadScript("assets/js/plugin/datatables/dataTables.tableTools.min.js", function(){
        loadScript("assets/js/plugin/datatables/dataTables.bootstrap.min.js", function(){
          loadScript("assets/js/plugin/datatable-responsive/datatables.responsive.min.js", pagefunction)
        });
      });
    });
  });

      </script>