<section id="widget-grid" class="">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h1 class="page-title txt-color-blueDark">
          <i class="fa-fw fa fa-graduation-cap"></i> Estudiante <?php echo strtoupper(Session::get('User'))?></h1>
      </div>
    </div>

    <div class="row">
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        	<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">
	            <header>
	              <span class="widget-icon"> <i class="fa fa-file"></i> </span>
	              <h2> Curriculum Vitae "Hoja de Vida" </h2>        
	            </header>
            	<div>
              		<div class="jarviswidget-editbox"></div>
            		<div class="widget-body no-padding">
						<ul id="myTab1" class="nav nav-tabs bordered">						
							<li class="active">
								<a href="#s1" data-toggle="tab"><i class="fa fa-lg fa-fw fa-user"></i> Generales</a>
							</li>
							<li>
								<a href="#s2" data-toggle="tab"><i class="fa fa-lg fa-fw fa-graduation-cap"></i> Datos Personales</a>
							</li>
							<li>
								<a href="#s3" data-toggle="tab"><i class="fa fa-fw fa-lg fa-dollar"></i> Referencias</a>
							</li>
							<li>
								<a href="#s4" data-toggle="tab"><i class="fa fa-fw fa-lg fa-dollar"></i> Educacion</a>
							</li>
							<li>
								<a href="#s5" data-toggle="tab"><i class="fa fa-fw fa-lg fa-dollar"></i> Experiencia laboral</a>
							</li>
							<li>
								<a href="#s6" data-toggle="tab"><i class="fa fa-fw fa-lg fa-dollar"></i> Informacion adicional</a>
							</li>
						</ul>

						<div id="myTabContent1" class="tab-content padding-10">
							<div class="tab-pane fade in active" id="s1">
								<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">
					            	<header>Datos Básicos</header>
						            <fieldset>
						            	<div class="row">
							            	<section class="col col-4">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Identificación">
							                    </label>
							                </section>
											<section class="col col-4">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Fecha de expedicion">
							                    </label>
							                </section>
							                <section class="col col-4">
												<label class="select">
													<select class="input-sm">
														<option value="0">Ciudad de Expedicion</option>
														<option value="1">Alexandra</option>
														<option value="2">Alice</option>
														<option value="3">Anastasia</option>
														<option value="4">Avelina</option>
													</select> <i></i> 
												</label>
											</section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-4">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Nro de libreta militar">
							                    </label>
							                </section>
											<section class="col col-4">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Distrito militar">
							                    </label>
							                </section>
							                <section class="col col-4">
												<label class="select">
													<select class="input-sm">
														<option value="0">Ciudad Lib. militar</option>
														<option value="1">Alexandra</option>
														<option value="2">Alice</option>
														<option value="3">Anastasia</option>
														<option value="4">Avelina</option>
													</select> <i></i> 
												</label>
											</section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
								            	<label class="input"> <i class="icon-prepend fa fa-briefcase"></i>
								                	<input type="text" name="razon" placeholder="Nombres">
								                </label>
							            	</section>
									        <section class="col col-6">
						                        <label class="input"> <i class="icon-prepend fa fa-map-marker"></i>
						                        	<input type="text" name="razon" placeholder="Apellido">
						                        </label>
					                    	</section>
					                    </div>
					                    <div class="row">
									        <section class="col col-3">
						                        <label class="input"> <i class="icon-prepend fa fa-map-marker"></i>
						                        	<input type="text" name="address" placeholder="Dirección">
						                        </label>
					                    	</section>
											<section class="col col-3">
									            	<label class="input"> <i class="icon-prepend fa fa-briefcase"></i>
									                	<input type="text" name="razon" placeholder="Barrio">
									                </label>
								           	</section>
								           	<section class="col col-3">
												<label class="select">
													<select class="input-sm">
														<option value="0">Estracto</option>
														<option value="1">1</option>
														<option value="2">2</option>
														<option value="3">3</option>
														<option value="4">4</option>
														<option value="5">5</option>
													</select> <i></i> 
												</label>
											</section>
								           	<section class="col col-3">
												<label class="select">
													<select class="input-sm">
														<option value="0">Ciudad</option>
														<option value="1">Alexandra</option>
														<option value="2">Alice</option>
														<option value="3">Anastasia</option>
														<option value="4">Avelina</option>
													</select> <i></i> 
												</label>
											</section>
					                    </div>
										<div class="row">
											<section class="col col-6">
						                        <label class="input"> <i class="icon-prepend fa fa-map-marker"></i>
						                        	<input type="text" name="address" placeholder="Telefono">
						                        </label>
					                    	</section>
					                    	<section class="col col-6">
						                        <label class="input"> <i class="icon-prepend fa fa-map-marker"></i>
						                        	<input type="text" name="address" placeholder="Celular">
						                        </label>
					                    	</section>
										</div>
										<div class="row">
											<section class="col col-6">
						                        <label class="input"> <i class="icon-prepend fa fa-map-marker"></i>
						                        	<input type="text" name="address" placeholder="Email">
						                        </label>
					                    	</section>
					                    	<section class="col col-6">
						                        <label class="input"> <i class="icon-prepend fa fa-map-marker"></i>
						                        	<input type="text" name="address" placeholder="Pasado Judicial No.">
						                        </label>
					                    	</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="ON" data-swchoff-text="OFF"></i>Licencia Conducción
												</label>
					                    	</section>
					                    	<section class="col col-6">
						                        <label class="select">
													<select class="input-sm">
														<option value="0">Categoria</option>
														<option value="1">1</option>
														<option value="2">2</option>
														<option value="3">3</option>
														<option value="4">4</option>
														<option value="5">5</option>
														<option value="6">6</option>
														<option value="7">7</option>
														<option value="8">8</option>
													</select> <i></i> 
												</label>
					                    	</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Sisben
												</label>
											</section>	
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Pertenencia a red unidos
												</label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Cetificado Manipulacion Alimentos
												</label>
											</section>	
											<section class="col col-6">
												<label class="input"> <i class="icon-prepend fa fa-map-marker"></i>
						                        	<input type="text" name="address" placeholder="Expedida por">
						                        </label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Certificado Bioseguridad
												</label>
											</section>	
											<section class="col col-6">
												<label class="input"> <i class="icon-prepend fa fa-map-marker"></i>
						                        	<input type="text" name="address" placeholder="Expedida por">
						                        </label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Certificado de Trabajo en Altura
												</label>
											</section>	
											<section class="col col-6">
												<label class="input"> <i class="icon-prepend fa fa-map-marker"></i>
						                        	<input type="text" name="address" placeholder="Expedida por">
						                        </label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Certificado Conte
												</label>
											</section>	
											<section class="col col-6">
												<label class="input"> <i class="icon-prepend fa fa-map-marker"></i>
						                        	<input type="text" name="address" placeholder="Expedida por">
						                        </label>
											</section>
										</div>
										<section>
											<label class="textarea textarea-expandable">	
												<textarea rows="3" class="custom-scroll"></textarea> 
											</label>
											<div class="note">
												<strong>Nota:</strong> Se expande.
											</div>
										</section>
						            </fieldset>
					            </form>														
							</div>
							<div class="tab-pane fade" id="s2">
								<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">
									<header>Datos Personales</header>
					                <fieldset>
					                	<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Fecha de nacimiento">
							                    </label>
							                </section>
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="M" data-swchoff-text="F"></i>Sexo
												</label>
											</section>
						          		</div>
										<div class="row">
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Profesión/Oficio">
							                    </label>
							                </section>
											<section class="col col-6">
												<label class="select">
													<select class="input-sm">
														<option value="0">Estado Civil</option>
														<option value="1">Soltero</option>
														<option value="2">Casado</option>
														<option value="3">Divorciado</option>
														<option value="4">Union Libre</option>
													</select> <i></i> 
												</label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Peso">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Estatura">
							                    </label>
							                </section>
										</div>
										<div class="row">
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Talla de Zapato 	">
							                    </label>
							                </section>
											<section class="col col-6">
												<label class="select">
													<select class="input-sm">
														<option value="0">Tipo de sangre</option>
														<option value="1">O+</option>
														<option value="2">AB+</option>
														<option value="3">O-</option>
														<option value="4">AB-</option>
														<option value="5">A+</option>
														<option value="6">A-</option>
														<option value="7">B+</option>
														<option value="8">B-</option>
													</select> <i></i> 
												</label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Talla de Pantalon">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Talla de Camisa">
							                    </label>
							                </section>
										</div>
					                </fieldset>

									<header>
						                Grupo Étnico al que pertenece
						            </header>
									<fieldset>
										<div class="row">
												<section class="col col-4">
													<label class="select">
														<select class="input-sm">
															<option value="0">Grupo Étnico</option>
															<option value="1">Afrocolombiano</option>
															<option value="2">Indigena</option>
															<option value="3">Sin pertenencia étnica</option>
															<option value="4">Otros grupos</option>
														</select> <i></i> 
													</label>
												</section>
												<section class="col col-4">
													<label class="select">
														<select class="input-sm">
															<option value="0">Tipo de Étnia</option>
															<option value="1">Afrodecendiente</option>
															<option value="2">Negro</option>
															<option value="3">Palenquero</option>
															<option value="4">Raizal</option>
															<option value="5">Blanco</option>
															<option value="6">Mestizo</option>
															<option value="7">Arabes</option>
															<option value="8">Judios</option>
															<option value="9">Rom-Gitanos</option>
															<option value="10">Otros</option>
															<option value="11">N/A</option>
														</select> <i></i> 
													</label>
												</section>
											</div>
									</fieldset>

									<header>
						                Grupo social al que pertenece
						            </header>
						            <fieldset>
						            	<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Madre cabeza de familia
												</label>
											</section>	
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Desplazado por la violencia
												</label>
											</section>
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Desplazado por fenomeno natural
												</label>
											</section>	
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Reinsertado
												</label>
											</section>	
										</div>
										<div class="row">
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Discapacitado 	
												</label>
											</section>	
											<section class="col col-6">
												<label class="input"> <i class="icon-prepend fa fa-map-marker"></i>
						                        	<input type="text" name="address" placeholder="Discapacidad">
						                        </label>
											</section>
										</div>
						            </fieldset>

								</form>
							</div>
							
						     <div class="tab-pane fade" id="s3">
								<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">

									<header>
						                Familiares
						            </header>
						            <fieldset>
						            	<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Nombre">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Parentesco">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Edad">
							                    </label>
							                </section>
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="M" data-swchoff-text="F"></i>Sexo
												</label>
											</section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Ocupación">
							                    </label>
							                </section>
											<section class="col col-6">
													<label class="select">
														<select class="input-sm">
															<option value="0">Nivel de escolaridad 	</option>
															<option value="1">Bachiller</option>
															<option value="2">Técnico</option>
															<option value="3">Técnologo</option>
															<option value="4">Profesional</option>
															<option value="5">Basica Primaria</option>
														</select> <i></i> 
													</label>
												</section>
						          		</div>
						            </fieldset>

									<header>
						                Personales
						            </header>
						            <fieldset>
						            	<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Nombre">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Parentesco">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Direccion">
							                    </label>
							                </section>
											<section class="col col-6">
													<label class="select">
														<select class="input-sm">
															<option value="0">Ciudad</option>
															<option value="1">Bachiller</option>
															<option value="2">Técnico</option>
															<option value="3">Técnologo</option>
															<option value="4">Profesional</option>
															<option value="5">Basica Primaria</option>
														</select> <i></i> 
													</label>
												</section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Telefono">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Celular">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Profesión">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Empresa donde labora">
							                    </label>
							                </section>
						          		</div>
						            </fieldset>
						         </form>
						     </div>
						     <div class="tab-pane fade" id="s4">
								<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">
									<header>
						                Educación
						            </header>
						            <fieldset>
						            	<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Institucion">
							                    </label>
							                </section>
											<section class="col col-6">
													<label class="select">
														<select class="input-sm">
															<option value="0">Nivel</option>
															<option value="1">Bachiller</option>
															<option value="2">Técnico</option>
															<option value="3">Técnologo</option>
															<option value="4">Profesional</option>
															<option value="5">Basica Primaria</option>
														</select> <i></i> 
													</label>
												</section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Fecha de inicio">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Fecha de finalizacion">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Titulo">
							                    </label>
							                </section>
											<section class="col col-6">
													<label class="select">
														<select class="input-sm">
															<option value="0">Ciudad</option>
															<option value="1">Bachiller</option>
															<option value="2">Técnico</option>
															<option value="3">Técnologo</option>
															<option value="4">Profesional</option>
															<option value="5">Basica Primaria</option>
														</select> <i></i> 
													</label>
												</section>
						          		</div>
						            </fieldset>
						         </form>
						     </div>
						     <div class="tab-pane fade" id="s5">
								<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">
									<header>
						                Idioma
						            </header>
						            <fieldset>
						            	<div class="row">
						            		<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Idioma">
							                    </label>
							                </section>
							                <section class="col col-6">
													<label class="select">
														<select class="input-sm">
															<option value="0">Lee</option>
															<option value="1">E</option>
															<option value="2">B</option>
															<option value="3">M</option>
														</select> <i></i> 
													</label>
							                </section>
						            	</div>
						            	<div class="row">
						            		<section class="col col-6">
													<label class="select">
														<select class="input-sm">
															<option value="0">Habla</option>
															<option value="1">E</option>
															<option value="2">B</option>
															<option value="3">M</option>
														</select> <i></i> 
													</label>
							                </section>
							                <section class="col col-6">
													<label class="select">
														<select class="input-sm">
															<option value="0">Escribe</option>
															<option value="1">E</option>
															<option value="2">B</option>
															<option value="3">M</option>
														</select> <i></i> 
													</label>
							                </section>
						            	</div>
						            </fieldset>
									<header>
						                Experiencia Laboral
						            </header>
						            <fieldset>
						            	<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Empresa">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Cargo">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Fecha de inicio">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Fecha de finalizacion">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Funciones">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Teléfono">
							                    </label>
							                </section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Nombre del Jefe inmediato">
							                    </label>
							                </section>
											<section class="col col-6">
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Motivo de retiro">
							                    </label>
							                </section>
						          		</div>
						            </fieldset>
						         </form>
						     </div>
						     
						     <div class="tab-pane fade" id="s6">
								<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">
									<header>
							                Informacion Bancaria
							            </header>
							            <fieldset>
							            	<div class="row">
								            	<section class="col col-6">
													<label class="toggle">
														<input type="checkbox" name="checkbox-toggle">
														<i data-swchon-text="SI" data-swchoff-text="NO"></i>Cuenta Bancaria
													</label>
												</section>
												<section class="col col-6">
														<label class="select">
															<select class="input-sm">
																<option value="0">Tipo de cuenta</option>
																<option value="1">Ceunta de ahorro</option>
																<option value="2">Cuenta corriente</option>
															</select> <i></i> 
														</label>
								                </section>
							          		</div>
							          		<div class="row">
								            	<section class="col col-6">
								                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
								                    	<input type="text" name="e_id" placeholder="Banco">
								                    </label>
								                </section>
												<section class="col col-6">
													<label class="toggle">
														<input type="checkbox" name="checkbox-toggle">
														<i data-swchon-text="SI" data-swchoff-text="NO"></i>¿Esta Activa?
													</label>
												</section>
							          		</div>
							            </fieldset>
									<header>
						                Informacion adicional
						            </header>
						            <fieldset>
						            	<div class="row">
							            	<section class="col col-6">
													<label class="select">
														<select class="input-sm">
															<option value="0">Vivienda en la que habita</option>
															<option value="1">Propia</option>
															<option value="2">Alquilada</option>
															<option value="3">Invasión</option>
															<option value="4">Familiar</option>
														</select> <i></i> 
													</label>
							                </section>
											<section class="col col-6">
													<label class="select">
														<select class="input-sm">
															<option value="0">Material de los exteriores de la vivienda</option>
															<option value="1">Ladrillo/Bloque</option>
															<option value="2">Material prefabricado</option>
															<option value="2">Madera pulida</option>
															<option value="2">Piedra</option>
															<option value="2">Adobe</option>
															<option value="2">Baldosin</option>
															<option value="2">Unisol</option>
															<option value="2">Marmol</option>
															<option value="2">Alfombra/Tapete</option>
														</select> <i></i> 
													</label>
							                </section>
						          		</div>
						          		<div class="row">
						          		<label>¿Cuenta con servivios publicos?</label><br>
							            	<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Agua
												</label>
											</section>
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Energia Electrica
												</label>
											</section>
						          		</div>
						          		<div class="row">
							            	<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Alcantarillado 	
												</label>
											</section>
											<section class="col col-6">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Gas
												</label>
											</section>
						          		</div>
						          		<div class="row">
						          		<section section class="col col-4">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Télefono
												</label>
											</section>
						          			<section class="col col-4">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Conyugue
												</label>
											</section>
							            	<section class="col col-4">
												<label class="toggle">
													<input type="checkbox" name="checkbox-toggle">
													<i data-swchon-text="SI" data-swchoff-text="NO"></i>Trabaja
												</label>
											</section>
						          		</div>
						          		<div class="row">
						          			<section>
							                	<label class="input"> <i class="icon-prepend glyphicon glyphicon-barcode"></i>
							                    	<input type="text" name="e_id" placeholder="Promedio de ingreso mensual">
							                    </label>
							                </section>
						          		</div>
						            </fieldset>
						         </form>
						     </div>
						</div>
						<div class="modal fade" id="newContract" tabindex="-1" role="dialog" aria-labelledby="remoteModalLabel" aria-hidden="true">  
						     <div class="modal-dialog">  
						         <div class="modal-content">
						            
						         </div>  
						     </div>
						</div>					  
						<div class="widget-footer">
							<button type="button" class="btn btn-primary" data-dismiss="modal">
								Guardar
							</button>
						</div>
					</div>
            	</div>
        	</div>
        </article>       
    </div>

</section>