<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
		&times;
	</button>
	<h4 class="modal-title" id="myModalLabel"><?php echo $this->student['nombre'].' - '.$this->student['e_identificacion']; ?></h4>
</div>

<div class="modal-body">
	<ul id="myTab1" class="nav nav-tabs bordered">
							<li class="active">
								<a href="#s1" data-toggle="tab">
									<i class="fa fa-lg fa-fw fa-user"></i> Datos Personales 
								</a>
								<!-- <span class="badge bg-color-blue txt-color-white">12</span> -->
							</li>
							<li>
								<a href="#s2" data-toggle="tab"><i class="fa fa-lg fa-fw fa-graduation-cap"></i> Estudios</a>
							</li>
							<li>
								<a href="#s2" data-toggle="tab"><i class="fa fa-fw fa-lg fa-briefcase"></i> Laboral</a>
							</li>
							<li>
								<a href="#s2" data-toggle="tab"><i class="fa fa-fw fa-lg fa-dollar"></i>Contratación</a>
							</li>
						</ul>

						<div id="myTabContent1" class="tab-content padding-10">
							<div class="tab-pane fade in active" id="s1">
								

								
							</div>
							<div class="tab-pane fade" id="s2">
								<p>
									Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee.
								</p>
							</div>
							<div class="tab-pane fade" id="s3">
								<p>
									Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony.
								</p>
							</div>
							<div class="tab-pane fade" id="s4">
								<p>
									Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table.
								</p>
							</div>
						</div>


</div>

<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">
		Cerrar
	</button>
</div>