<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
		&times;
	</button>
	<h4 class="modal-title" id="myModalLabel">Evaluación <?php echo '' ?></h4>
</div>

<div class="modal-body">
	<form action="" id="checkout-form" class="smart-form" novalidate="novalidate">
        <fieldset>
        	<div class="row">
            	<section class="col col-6">
                	<label class="input"> <i class="icon-prepend fa fa-calendar"></i>
                    	<input type="date" name="e_id" placeholder="Fecha">
                    </label>
                </section>
                <section class="col col-6">
	            	<label class="input"> <i class="icon-prepend fa fa-star-half-full "></i>
	                	<input type="text" name="razon" placeholder="Promedio Calificación">
	                </label>
            	</section>
      		</div>
            <section>
                <label class="checkbox">
					<input type="checkbox" name="subscription" id="subscription">
					<i></i> Aprobado</label>
    		</section>
        	<section>
        		<label class="textarea"> 										
					<textarea rows="3" name="info" placeholder="Observaciones"></textarea> 
				</label>
        	</section>
        </fieldset>
    </form>											
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">
		Guardar
	</button>
</div>