<ul>
  
  <?php if(Session::get('level')==1){ ?>
    <li class="">
      <a href="/RILE/estudiantes/profile" title="Menu Estudiantes">
        <i class="fa fa-lg fa-fw fa-graduation-cap"></i> <span
         class="menu-item-parent">Estudiantes</span>
      </a>
    </li>
  <?php } ?>

  <?php if(Session::get('level')==2){ ?>
      <li>
        <a href="/RILE/empresas" title="Menu Empresas">
          <i class="fa fa-lg fa-fw fa-building"></i> <span
           class="menu-item-parent">Menu Empresas</span>
        </a>
      </li>
  <?php } ?>

  <?php if(Session::get('level')>2){ ?>
    <li class="">
    <a href="/RILE/dashboard" title="RILE > Dashboard">
      <i class="fa fa-lg fa-fw fa-home"></i> 
      <span class="menu-item-parent">Dashboard</span>
    </a>
    </li>
    <li class="">
      <a href="#" title="RILE > Solicitudes">
        <i class="fa fa-lg fa-fw fa-briefcase"></i> 
        <span class="menu-item-parent">Solicitudes</span>
      </a>
      <ul>
        <li>
          <a href="/RILE/solicitudes">Listado</a>
        </li>
        <li>
          <a href="/RILE/solicitudes/nuevo">Crear</a>
        </li>
      </ul>
    </li>
    <li class="">
      <a href="/RILE/estudiantes" title="Estudiantes">
        <i class="fa fa-lg fa-fw fa-graduation-cap"></i> 
        <span class="menu-item-parent">Estudiantes</span>
      </a>
    </li>
    <li>
      <a href="/RILE/empresas" title="Empresas">
        <i class="fa fa-lg fa-fw fa-building"></i> 
        <span class="menu-item-parent">Empresas</span>
      </a>
    </li>
    <li>
      <a href="/RILE/contratos" title="Contratos">
        <i class="fa fa-lg fa-fw fa-table"></i> 
        <span class="menu-item-parent">Contratos</span>
      </a>
    </li>
    <li>
      <a href="#" title="Actas">
        <i class="fa fa-lg fa-fw fa-pencil-square-o"></i> 
        <span class="menu-item-parent">Actas</span>
      </a>
    </li>
    <li>
      <a href="#" title="Seguimiento">
        <i class="fa fa-lg fa-fw fa-crosshairs"></i> 
        <span class="menu-item-parent">Seguimiento</span>
      </a>
    </li>
    <li>
      <a href="/RILE/alertas" title="Alertas">
        <i class="fa fa-lg fa-fw fa-bell-o"><em>3</em></i> 
        <span class="menu-item-parent">Alertas</span>
      </a>
    </li>
    <li>
      <a href="/RILE/configuracion">
        <i class="fa fa-lg fa-fw fa-cogs txt-color-blue"></i> 
        <span class="menu-item-parent">Configuración</span>
      </a>
    </li>
    <?php } ?>
</ul>
