<ul>
  <li class="">
    <a href="/RILE/dashboard" title="RILE > Dashboard"><i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">Dashboard</span></a>
  </li>
<li class="">
    <a href="/RILE/estudiantes" title="RILE > Estudiantes"><i class="fa fa-lg fa-fw fa-graduation-cap"></i> <span class="menu-item-parent">Estudiantes</span></a>
  </li>
  <li>
    <a href="/RILE/empresas" title="RILE > Empresas"><i class="fa fa-lg fa-fw fa-briefcase"></i> <span class="menu-item-parent">Empresas</span></a>
  </li>
  <li>
    <a href="/RILE/contratos"><i class="fa fa-lg fa-fw fa-table"></i> <span class="menu-item-parent">Contratos</span></a>
  </li>
  <li>
    <a href="#"><i class="fa fa-lg fa-fw fa-pencil-square-o"></i> <span class="menu-item-parent">Actas</span></a>
    <ul>
      <li>
        <a href="ajax/form-elements.html">Smart Form Elements</a>
      </li>
      <li>
        <a href="ajax/form-templates.html">Smart Form Layouts</a>
      </li>
      <li>
        <a href="ajax/validation.html">Smart Form Validation</a>
      </li>
      <li>
        <a href="ajax/bootstrap-forms.html">Bootstrap Form Elements</a>
      </li>
      <li>
        <a href="ajax/plugins.html">Form Plugins</a>
      </li>
      <li>
        <a href="ajax/wizard.html">Wizards</a>
      </li>
      <li>
        <a href="ajax/other-editors.html">Bootstrap Editors</a>
      </li>
      <li>
        <a href="ajax/dropzone.html">Dropzone</a>
      </li>
      <li>
        <a href="ajax/image-editor.html">Image Cropping <span class="badge pull-right inbox-badge bg-color-yellow">new</span></a>
      </li>
    </ul>
  </li>
  <li>
    <a href="#"><i class="fa fa-lg fa-fw fa-crosshairs"></i> <span class="menu-item-parent">Seguimiento</span></a>
    <ul>
      <li>
        <a href="ajax/general-elements.html">General Elements</a>
      </li>
      <li>
        <a href="ajax/buttons.html">Buttons</a>
      </li>
      <li>
        <a href="#">Icons</a>
        <ul>
          <li>
            <a href="ajax/fa.html"><i class="fa fa-plane"></i> Font Awesome</a>
          </li>
          <li>
            <a href="ajax/glyph.html"><i class="glyphicon glyphicon-plane"></i> Glyph Icons</a>
          </li>
          <li>
            <a href="ajax/flags.html"><i class="fa fa-flag"></i> Flags</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="ajax/grid.html">Grid</a>
      </li>
      <li>
        <a href="ajax/treeview.html">Tree View</a>
      </li>
      <li>
        <a href="ajax/nestable-list.html">Nestable Lists</a>
      </li>
      <li>
        <a href="ajax/jqui.html">JQuery UI</a>
      </li>
      <li>
        <a href="ajax/typography.html">Typography</a>
      </li>
      <li>
        <a href="#">Six Level Menu</a>
        <ul>
          <li>
            <a href="#"><i class="fa fa-fw fa-folder-open"></i> Item #2</a>
            <ul>
              <li>
                <a href="#"><i class="fa fa-fw fa-folder-open"></i> Sub #2.1 </a>
                <ul>
                  <li>
                    <a href="#"><i class="fa fa-fw fa-file-text"></i> Item #2.1.1</a>
                  </li>
                  <li>
                    <a href="#"><i class="fa fa-fw fa-plus"></i> Expand</a>
                    <ul>
                      <li>
                        <a href="#"><i class="fa fa-fw fa-file-text"></i> File</a>
                      </li>
                      <li>
                        <a href="#"><i class="fa fa-fw fa-trash-o"></i> Delete</a></li>
                      </ul>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
            <li>
              <a href="#"><i class="fa fa-fw fa-folder-open"></i> Item #3</a>

              <ul>
                <li>
                  <a href="#"><i class="fa fa-fw fa-folder-open"></i> 3ed Level </a>
                  <ul>
                    <li>
                      <a href="#"><i class="fa fa-fw fa-file-text"></i> File</a>
                    </li>
                    <li>
                      <a href="#"><i class="fa fa-fw fa-file-text"></i> File</a>
                    </li>
                  </ul>
                </li>
              </ul>

            </li>
          </ul>
        </li>
      </ul>
    </li>
    <li>
      <a href="ajax/calendar.html"><i class="fa fa-lg fa-fw fa-bell-o"><em>3</em></i> <span class="menu-item-parent">Alertas</span></a>
      <ul>
        <li>
          <a href="#">Finalización etapa Electiva</a>
        </ll>
        <li>
          <a href="ajax/forum.html">Finalización etapa Productiva</a>
        </li>
        <li>
          <a href="ajax/profile.html">Etaps productivas Vencidas</a>
        </li>
        <li>
          <a href="ajax/timeline.html">Entravistados</a>
        </li>
        <li>
          <a href="ajax/timeline.html">Finalización en 60 dias</a>
        </li>
      </ul> 
    </li>
    <li>
      <a href="ajax/widgets.html"><i class="fa fa-lg fa-fw fa-list-alt"></i> <span class="menu-item-parent">Widgets</span></a>
    </li>
    <li>
      <a href="ajax/gallery.html"><i class="fa fa-lg fa-fw fa-picture-o"></i> <span class="menu-item-parent">Gallery</span></a>
    </li>
    <li>
      <a href="ajax/gmap-xml.html"><i class="fa fa-lg fa-fw fa-map-marker"></i> <span class="menu-item-parent">GMap Skins</span><span class="badge bg-color-greenLight pull-right inbox-badge">9</span></a>
    </li>
    <li>
      <a href="#"><i class="fa fa-lg fa-fw fa-bar-chart-o"></i> <span class="menu-item-parent">Indicadores</span></a>
      <ul>
        <li>
          <a href="#"><i class="fa fa-file"></i> Other Pages</a>
          <ul>
            <li>
              <a href="ajax/forum.html">Forum Layout</a>
            </li>
            <li>
              <a href="ajax/profile.html">Profile</a>
            </li>
            <li>
              <a href="ajax/timeline.html">Timeline</a>
            </li>
          </ul> 
        </li>
        <li>
          <a href="ajax/pricing-table.html">Pricing Tables</a>
        </li>
        <li>
          <a href="ajax/invoice.html">Invoice</a>
        </li>
        <li>
          <a href="login.html" target="_top">Login</a>
        </li>
        <li>
          <a href="register.html" target="_top">Register</a>
        </li>
        <li>
          <a href="lock.html" target="_top">Locked Screen</a>
        </li>
        <li>
          <a href="ajax/error404.html">Error 404</a>
        </li>
        <li>
          <a href="ajax/error500.html">Error 500</a>
        </li>
        <li>
          <a href="ajax/blank_.html">Blank Page</a>
        </li>
        <li>
          <a href="ajax/email-template.html">Email Template</a>
        </li>
        <li>
          <a href="ajax/search.html">Search Page</a>
        </li>
        <li>
          <a href="ajax/ckeditor.html">CK Editor</a>
        </li>
      </ul>
    </li>
    <li class="top-menu-hidden">
      <a href="#"><i class="fa fa-lg fa-fw fa-cogs txt-color-blue"></i> <span class="menu-item-parent">Configuración</span></a>
      <ul>
        <li>
          <a href="ajax/difver.html"><i class="fa fa-money"></i> SMLV</a>
        </li>
        <li>
          <a href="ajax/difver.html"><i class="fa fa-stack-overflow"></i> Convenios</a>
        </li>
        <li>
          <a href="ajax/applayout.html"><i class="fa fa-mortar-board"></i> Programas</a>
        </li>
        <li>
          <a href="http://bootstraphunter.com/smartadmin/BUGTRACK/track_/documentation/index.html" target="_blank"><i class="fa fa-cubes"></i> Modulos</a>
        </li>
        <li>
          <a href="http://bootstraphunter.com/smartadmin/BUGTRACK/track_/" target="_blank"><i class="fa fa-group"></i> Usuarios</a>
        </li>
        <li>
          <a href="http://bootstraphunter.com/smartadmin/BUGTRACK/track_/" target="_blank"><i class="glyphicon glyphicon-user"></i> Perfil</a>
        </li>
      </ul>
    </li>
  </ul>
