<ul>
  <li class="">
    <a href="/RILE/dashboard" title="RILE > Dashboard"><i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">Dashboard</span></a>
  </li>
  <li class="">
    <a href="/RILE/estudiantes" title="RILE > Solicitudes"><i class="fa fa-lg fa-fw fa-briefcase"></i> <span class="menu-item-parent">Solicitudes</span></a>
    <ul>
      <li>
        <a href="/RILE/solicitudes/nuevo">Crear</a>
      </li>
      <li>
        <a href="/RILE/solicitudes">Listado</a>
      </li>
    </ul>
  </li>
  <li class="">
    <a href="/RILE/estudiantes" title="RILE > Estudiantes"><i class="fa fa-lg fa-fw fa-graduation-cap"></i> <span class="menu-item-parent">Estudiantes</span></a>
  </li>
  <li>
    <a href="/RILE/empresas" title="RILE > Empresas"><i class="fa fa-lg fa-fw fa-building"></i> <span class="menu-item-parent">Empresas</span></a>
  </li>
  <li>
    <a href="/RILE/contratos"><i class="fa fa-lg fa-fw fa-table"></i> <span class="menu-item-parent">Contratos</span></a>
  </li>
  <li>
    <a href="#"><i class="fa fa-lg fa-fw fa-pencil-square-o"></i> <span class="menu-item-parent">Actas</span></a>
  </li>
  <li>
    <a href="#"><i class="fa fa-lg fa-fw fa-crosshairs"></i> <span class="menu-item-parent">Seguimiento</span></a>
  </li>
    <li>
      <a href="ajax/calendar.html"><i class="fa fa-lg fa-fw fa-bell-o"><em>3</em></i> <span class="menu-item-parent">Alertas</span></a>
      <ul>
        <li>
          <a href="#">Finalización etapa Electiva</a>
        </ll>
        <li>
          <a href="ajax/forum.html">Finalización etapa Productiva</a>
        </li>
        <li>
          <a href="ajax/profile.html">Etaps productivas Vencidas</a>
        </li>
        <li>
          <a href="ajax/timeline.html">Entravistados</a>
        </li>
        <li>
          <a href="ajax/timeline.html">Finalización en 60 dias</a>
        </li>
      </ul> 
    </li>
    <li class="top-menu-hidden">
      <a href="/RILE/configuracion"><i class="fa fa-lg fa-fw fa-cogs txt-color-blue"></i> <span class="menu-item-parent">Configuración</span></a>
      <!-- <ul>
        <li>
          <a href="/RILE/configuracion"><i class="fa fa-money"></i> SMLV</a>
        </li>
        <li>
          <a href="ajax/difver.html"><i class="fa fa-stack-overflow"></i> Convenios</a>
        </li>
        <li>
          <a href="ajax/applayout.html"><i class="fa fa-mortar-board"></i> Programas</a>
        </li>
        <li>
          <a href="http://bootstraphunter.com/smartadmin/BUGTRACK/track_/documentation/index.html" target="_blank"><i class="fa fa-cubes"></i> Modulos</a>
        </li>
        <li>
          <a href="http://bootstraphunter.com/smartadmin/BUGTRACK/track_/" target="_blank"><i class="fa fa-group"></i> Usuarios</a>
        </li>
        <li>
          <a href="http://bootstraphunter.com/smartadmin/BUGTRACK/track_/" target="_blank"><i class="glyphicon glyphicon-user"></i> Perfil</a>
        </li>
      </ul> -->
    </li>
  </ul>
