<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>BlackCore API Documentation</title>
	<?php
		$this->getCSS('bootstrap.min'); 
		$this->getCSS('font-awesome.min'); 
	?>

</head>
<body>
	
	<script type="text/x-handlebars">
		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
	</script>
	
	<?php
		$this->getJS("libs/jquery.min");
		$this->getJS("libs/underscore-min");
		$this->getJS("libs/bootstrap.min");
		$this->getJS("libs/handlebars.min");
		$this->getJS("libs/ember.min");
		$this->getJS("app");
	?>
</body>
</html>